# Generated by Django 5.2 on 2025-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
