# Generated by Django 5.2.1 on 2025-05-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_roomparticipant_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
