# Generated by Django 5.2.1 on 2025-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
